name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Decode BASEURL
      run: echo BASE_URL=\"https://fake.api.com/\" > ./local.properties
      
    - name: Decode clientId
      run: echo clientId=\"fakeApiKey\" > ./local.properties
          
    - name: Debug Build with Gradle
      run: ./gradlew clean assembleDebug --stacktrace
